version: '3.5'
services:
  discord:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./discord-clone
    volumes:
      - /app/node_modules
      - ./discord-clone:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
